name: poc-monitoring
summary: PoC for Monitoring created for Ubuntu Core.
description: |
  A simple PoC for monitoring and other tasks written in Go.
  Packaged as a Snap application using Snapcraft.
version: '1.0'
confinement: strict

plugs:
  custom-first:
    interface: system-files
    read:
      - /usr/bin/free
  custom-second:
    interface: system-files
    read:
      - /usr/bin
    write:
      - /usr/bin

apps:
  # monitoring
  monitoring:
    command: bin/Monitoring
    plugs:
      - hardware-observe
      - system-observe
      - mount-observe
      - process-control
      - cpu-control
      - custom-first
      - custom-second

  # logging
  logging:
    command: bin/Logging
    plugs:
      - log-observe

  # install
  install:
    command: bin/Install
    plugs:
      - snapd-control
      - home
      - network
      - personal-files
      - account-control


parts:
  poc-root:
    plugin: go
    go-packages:
      - github.com/francescobianca/PoC-Monitoring-Golang/Monitoring
      - github.com/francescobianca/PoC-Monitoring-Golang/Logging
      - github.com/francescobianca/PoC-Monitoring-Golang/Install
    source: .
    go-importpath: github.com/francescobianca/PoC-Monitoring-Golang
    stage-packages:
      - curl

architectures:
  - build-on: amd64
    run-on: all
