name: poc-monitoring
summary: PoC for Monitoring created for Ubuntu Core.
description: |
  A simple PoC for monitoring and other tasks written in Go.
  Packaged as a Snap application using Snapcraft.
version: '1.0'
confinement: strict

plugs:
  run-systemd-sessions:
    interface: system-files
    read:
      - $SNAP/bin
    write:
      - $SNAP/bin

apps:
  # monitoring
  monitoring:
    command: bin/Monitoring
    plugs:
      - hardware-observe
      - system-observe
      - run-systemd-sessions

  # logging
  logging:
    command: bin/Logging
    plugs:
      - log-observe

  # install
  install:
    command: bin/Install
    plugs:
      - snapd-control
      - home


parts:
  poc-root:
    plugin: go
    go-packages:
      - github.com/francescobianca/PoC-Monitoring-Golang/Monitoring
      - github.com/francescobianca/PoC-Monitoring-Golang/Logging
      - github.com/francescobianca/PoC-Monitoring-Golang/Install
    source: .
    go-importpath: github.com/francescobianca/PoC-Monitoring-Golang

architectures:
  - build-on: amd64
    run-on: all
